on: [push]
name: React Testing

jobs:
    build:
        name: Build solution
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                node-version: '12'

            - name: yarn
              run: |
                 ls
                 cd actions-app
                 yarn install
                 yarn test
                 

                